sudo: true
language: python
matrix:
  include:
  - python: 3.6
  - python: 3.7
cache: pip
install:
- pip install -r requirements-dev.txt
- python setup.py install
script:
- python test.py
- coveralls
before_deploy:
- python setup.py sdist bdist_wheel
deploy:
  provider: pypi
  user: __token__
  skip_existing: true
  on:
    tags: true
    branch: master
    distributions: sdist bdist_wheel
  password:
    secure: DqCDU9SW+o9BoOLqB0hXn74nXAaNw9FO2DXim6wrx+hBbfRWl6/r22Cm2D/x3slY7PtJHf/m//ztnPR+LDLNiz+73eFrDT6Smenryqrue7vrFnQ4nv/8iVfNzaQG3E+aYNBZMnIkuzqNHhISc+PhlRI0f2m4NUkx1iwkxjGfN0C233/VhnUCf2iXo6S2vbv6ABn8GUUlGz9NhsmecYdOcxdDUFHR0RF+a9CRSSueO60b/w80deXNpaq4WEORsTYQx1JpLPPFyYSet50/FZaLpQ1s/T5U+PM93fC7eiZgJGndndPj6lGZjAfETm9zGWJCnhUlo8qzX0kr02igrzVYhnChLjDVAYILI2PXqv7901NpzpmkVdeOLkC/WR8KHukU2T34WPkdUQ7f6FNdl7ukwdHQMjsRJe3PDBuZbqejEI1WcoUYFpwZdIQmDi8M1QmfpQxRIppq9tmmZC2hlxpk8EqBCAu8Z0CV85lQ9PjiZrWlRZEbgApgo7MBQzdbWfyNo+h/d0qRULZUQRxFkhV8lFDxuJmvmJI0zaH7sI1X33pI08upGB1PSncek4iZoRE9OPXdYeEAgh3OC4uDdBwqb25tOdXUxS7Hq8VPsXmybqX5qnfYxcnOAKQ3e8xsUip+zw7MFSsZvw0j7h1ACOkbR5/0ClQpxFOs/vdMV2ygEs4=
